changelog:
  exclude:
    labels:
      - dont-mention
  categories:
    - title: ⚠️ Breaking Changes
      labels:
        - breaking-change
    - title: ⚙️ New Features
      labels:
        - enhancement
    - title: 🐛 Bugfixes
      labels:
        - bug
    - title: 💋 Cosmetic Changes
      labels:
        - cosmetic
    - title: Other Changes
      labels:
        - "*"